// Set the start date for day unlocking.
// Day 1 unlocks on START_DATE, Day 2 on START_DATE + 1 day, etc.
export const START_DATE = new Date('2026-01-05T00:00:00');

// Per-day configuration. flagHash is the SHA-256 hex digest of the correct flag.
export const DAYS = [
  {
    day: 0,
    enabled: true,
    title: 'Setup',
    description: 'Set up your local environment, deploy a test chart, and retrieve the flag from the pod logs.',
    flagHash: '1c015e563e5e30188378f8516b89cfa5c6c14ba00f9efd5a878a570e383e2e03',
    chartUrl: 'https://example.com/charts/day00.tgz',
    setup: [
      '<strong>1. Install Docker</strong> (<a href="https://docs.docker.com/get-docker/" target="_blank" rel="noopener">docs</a>)',
      '<code>docker --version</code>',
      '<strong>2. Install kubectl</strong> (<a href="https://kubernetes.io/docs/tasks/tools/" target="_blank" rel="noopener">docs</a>)',
      '<code>kubectl version --client</code>',
      '<strong>3. Install kind</strong> (<a href="https://kind.sigs.k8s.io/docs/user/quick-start/#installation" target="_blank" rel="noopener">docs</a>)',
      '<code>kind --version</code>',
      '<strong>4. Install Helm</strong> (<a href="https://helm.sh/docs/intro/install/" target="_blank" rel="noopener">docs</a>)',
      '<code>helm version</code>',
      '<strong>5. Create a kind cluster</strong>',
      '<code>kind create cluster --name adventofkube</code>',
      '<strong>6. Install the Day 0 chart</strong>',
      '<code>helm install day00 oci://ghcr.io/adventofkube/charts/day00 --version 0.1.0</code>',
      '<strong>8. Get the flag from the pod logs</strong>',
      '<code>kubectl logs -n day00 setup-check</code>',
    ],
    hints: [
      'Make sure Docker is running before creating the kind cluster.',
      'If <code>kind create cluster</code> fails, try <code>docker ps</code> to check that Docker is responsive.',
      'On Linux, you may need to run Docker commands with <code>sudo</code> or add your user to the <code>docker</code> group.',
      'If the pod isn\'t showing logs yet, run <code>kubectl get pods -n day00</code> and wait for it to complete.',
    ],
    docs: [
      { title: 'Install kubectl', url: 'https://kubernetes.io/docs/tasks/tools/' },
      { title: 'kind Quick Start', url: 'https://kind.sigs.k8s.io/docs/user/quick-start/' },
      { title: 'Install Helm', url: 'https://helm.sh/docs/intro/install/' },
      { title: 'kubectl Cheat Sheet', url: 'https://kubernetes.io/docs/reference/kubectl/cheatsheet/' },
    ],
  },
  {
    day: 1,
    enabled: true,
    title: 'Broken Pod',
    description: 'A pod won\'t start. Something looks off about it. Find and fix the issue, then check the logs for the flag.',
    flagHash: 'd88ee18014da63147665ad1455bada2141eb3ba3bbb11051053a74ab2e3aa5c7',
    chartUrl: 'https://example.com/charts/day01.tgz',
    setup: [
      'Install the chart:',
      '<code>helm install day01 oci://ghcr.io/adventofkube/charts/day01 --version 0.2.0</code>',
      'Start investigating:',
      '<code>kubectl get pods -n day01</code>',
      'Once the pod is running, get the flag:',
      '<code>kubectl logs -n day01 day01-pod</code>',
    ],
    hints: [
      'Check the pod status and events:<code>kubectl get pods -n day01\nkubectl describe pod day01-pod -n day01</code>Look at the Events section at the bottom.',
      'The Events mention a failed image pull. Look closely at the image name — does it look right?',
      'The image name is <code>daay01</code> (with two a\'s). It should be <code>day01</code>. Delete the pod and recreate it with the correct image:<code>kubectl get pod day01-pod -n day01 -o yaml > fix.yaml\n# Edit fix.yaml: change daay01 to day01\nkubectl delete pod day01-pod -n day01\nkubectl apply -f fix.yaml</code>',
    ],
    docs: [
      { title: 'kubectl get', url: 'https://kubernetes.io/docs/reference/kubectl/generated/kubectl_get/' },
      { title: 'kubectl describe', url: 'https://kubernetes.io/docs/reference/kubectl/generated/kubectl_describe/' },
      { title: 'kubectl logs', url: 'https://kubernetes.io/docs/reference/kubectl/generated/kubectl_logs/' },
      { title: 'Debugging Pods', url: 'https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/' },
    ],
  },
  {
    day: 2,
    enabled: true,
    title: 'CrashLoop Detective',
    description: 'A pod is stuck in CrashLoopBackOff. Investigate the logs and fix the underlying issue to reveal the flag.',
    flagHash: '8c857417f96462d860c62550a7741cbfcb5f97c2b68ddb09bc5fc8332e43ddab',
    chartUrl: 'https://example.com/charts/day02.tgz',
    setup: [
      'Install the chart:',
      '<code>helm install day02 oci://ghcr.io/adventofkube/charts/day02 --version 0.1.0</code>',
      'Start investigating:',
      '<code>kubectl get pods -n day02</code>',
      'Check the pod logs:',
      '<code>kubectl logs -n day02 day02-pod</code>',
      'Once the pod is running, get the flag:',
      '<code>kubectl logs -n day02 day02-pod</code>',
    ],
    hints: [
      'Run <code>kubectl logs -n day02 day02-pod</code> to see why the pod is crashing. The error message should point you in the right direction.',
      'The logs say <code>FLAG_VALUE</code> is not set. The pod loads env vars from a ConfigMap via <code>envFrom</code>. Check which ConfigMap is referenced:<code>kubectl get pod day02-pod -n day02 -o yaml | grep configMapRef -A 1</code>',
      'The pod references <code>day02-settings</code>, but the actual ConfigMap is named <code>day02-config</code>:<code>kubectl get configmap -n day02</code>Export the pod, fix the reference, delete and recreate:<code>kubectl get pod day02-pod -n day02 -o yaml > fix.yaml\n# Edit fix.yaml: change day02-settings to day02-config\nkubectl delete pod day02-pod -n day02\nkubectl apply -f fix.yaml</code>',
    ],
    docs: [
      { title: 'kubectl logs', url: 'https://kubernetes.io/docs/reference/kubectl/generated/kubectl_logs/' },
      { title: 'Debugging Pods', url: 'https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/' },
      { title: 'ConfigMaps', url: 'https://kubernetes.io/docs/concepts/configuration/configmap/' },
      { title: 'Define Environment Variables Using a ConfigMap', url: 'https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/' },
    ],
  },
  {
    day: 3,
    enabled: true,
    title: 'Label Mismatch',
    description: 'A Service exists but can\'t reach its backend pods. Something is off with the wiring. Find the issue and get the flag.',
    flagHash: 'bc64f86e6a230e279ff0a5e095a48e52d1e234525b748e64f27c1680913cdf12',
    chartUrl: 'https://example.com/charts/day03.tgz',
    setup: [
      'Install the chart:',
      '<code>helm install day03 oci://ghcr.io/adventofkube/charts/day03 --version 0.1.0</code>',
      'Check the pod is running:',
      '<code>kubectl get pods -n day03</code>',
      'Try to reach the service:',
      '<code>kubectl run curl --rm -it --image=curlimages/curl --restart=Never -n day03 -- curl http://flag-server</code>',
      'Once the service is working, the curl will return the flag.',
    ],
    hints: [
      'The pod is running, but the Service can\'t reach it. Check the Service endpoints:<code>kubectl get endpoints -n day03</code>If it shows no endpoints, the Service isn\'t finding any pods.',
      'Services find pods using label selectors. Compare the Service selector to the Pod labels:<code>kubectl get svc flag-server -n day03 -o jsonpath=\'{.spec.selector}\'</code><code>kubectl get pods -n day03 --show-labels</code>',
      'The Service selector is <code>app: my-app</code> but the Pod has label <code>app: myapp</code> (no hyphen). Edit the Service to fix the selector:<code>kubectl edit svc flag-server -n day03</code>Change <code>my-app</code> to <code>myapp</code>.',
    ],
    docs: [
      { title: 'Services', url: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { title: 'Labels and Selectors', url: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/' },
      { title: 'kubectl get endpoints', url: 'https://kubernetes.io/docs/reference/kubectl/generated/kubectl_get/' },
      { title: 'Debugging Services', url: 'https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/' },
    ],
  },
  {
    day: 4,
    enabled: false,
    title: 'Secret Rotation',
    description: 'A deployment references a Secret that has been rotated. The old key no longer works. Update the Secret and restart the pods to get the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day04.tgz',
  },
  {
    day: 5,
    enabled: false,
    title: 'Resource Quota Squeeze',
    description: 'A namespace has a ResourceQuota and your deployment exceeds it. Right-size the resource requests to fit within the quota and deploy successfully.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day05.tgz',
  },
  {
    day: 6,
    enabled: false,
    title: 'Broken Deployment',
    description: 'A Deployment is failing to roll out. There are 3 things wrong with it. Diagnose each issue and fix them. Once the pod is running, check its logs for the flag.',
    flagHash: '3d9822e477d0414cc8c153847fbb667394143b9301c816e2b9eb0efb8bb737e4',
    chartUrl: 'https://example.com/charts/day06.tgz',
    setup: [
      'Install the chart:',
      '<code>helm install day06 oci://ghcr.io/adventofkube/charts/day06 --version 0.1.0</code>',
      'Start investigating:',
      '<code>kubectl get pods -n day06</code>',
      'Once all issues are fixed and the pod is running, get the flag:',
      '<code>kubectl logs -n day06 -l app=day06</code>',
    ],
    hints: [
      'Check the pod status and events:<code>kubectl get pods -n day06\nkubectl describe pod -n day06 -l app=day06</code>Look at the Events section — what does it say about the image?',
      'The image tag <code>v2</code> doesn\'t exist. Edit the Deployment to fix it:<code>kubectl edit deployment day06 -n day06</code>Change the image tag to one that exists. Try <code>v1</code>.',
      'After fixing the image, the pod crashes. Check the logs:<code>kubectl logs -n day06 -l app=day06</code>The error message tells you exactly what\'s missing.',
      'The app needs <code>APP_KEY</code>. There\'s a ConfigMap with the value:<code>kubectl get configmap -n day06\nkubectl describe configmap day06-config -n day06</code>Add an <code>envFrom</code> or <code>env</code> block to the Deployment referencing the ConfigMap.',
      'The pod is running but the port is wrong. Compare:<code>kubectl get deployment day06 -n day06 -o jsonpath=\'{.spec.template.spec.containers[0].ports}\'</code>The app listens on <code>8080</code>, not <code>80</code>. Fix <code>containerPort</code> in the Deployment.',
    ],
    docs: [
      { title: 'Deployments', url: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/' },
      { title: 'ConfigMaps', url: 'https://kubernetes.io/docs/concepts/configuration/configmap/' },
      { title: 'Container Ports', url: 'https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#ports' },
      { title: 'kubectl describe', url: 'https://kubernetes.io/docs/reference/kubectl/generated/kubectl_describe/' },
      { title: 'kubectl logs', url: 'https://kubernetes.io/docs/reference/kubectl/generated/kubectl_logs/' },
    ],
  },
  {
    day: 7,
    enabled: false,
    title: 'Ingress Maze',
    description: 'Multiple Ingress rules are conflicting. Fix the routing so traffic reaches the correct backend service to return the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day07.tgz',
  },
  {
    day: 8,
    enabled: false,
    title: 'Job Failure Analysis',
    description: 'A Job keeps failing after 3 attempts. Diagnose why it fails, fix the issue, and let it run to completion to output the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day08.tgz',
  },
  {
    day: 9,
    enabled: false,
    title: 'RBAC Lockdown',
    description: 'A ServiceAccount can\'t read the Secret containing the flag. Create the right Role and RoleBinding to grant access.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day09.tgz',
  },
  {
    day: 10,
    enabled: false,
    title: 'NetworkPolicy Firewall',
    description: 'A pod has the flag but a NetworkPolicy is blocking all traffic to it. Write a policy that allows only your debug pod to reach it.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day10.tgz',
  },
  {
    day: 11,
    enabled: false,
    title: 'Node Affinity Puzzle',
    description: 'A pod is stuck Pending because of node affinity rules that don\'t match any node. Fix the affinity or label the nodes correctly to schedule the pod.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day11.tgz',
  },
  {
    day: 12,
    enabled: false,
    title: 'PV Reclaim',
    description: 'A PersistentVolume has the flag on disk but its reclaim policy and claim are misconfigured. Fix the PV/PVC binding to mount the data.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day12.tgz',
  },
  {
    day: 13,
    enabled: false,
    title: 'ConfigMap Surgery',
    description: 'Multiple deployments share a ConfigMap but one needs different values. Refactor without breaking the others, then roll out to get the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day13.tgz',
  },
  {
    day: 14,
    enabled: false,
    title: 'Probes Gone Wrong',
    description: 'Liveness and readiness probes are misconfigured, causing a pod to restart endlessly or never receive traffic. Fix the probes to stabilize the deployment and get the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day14.tgz',
  },
  {
    day: 15,
    enabled: false,
    title: 'Taint Toleration',
    description: 'The only node with available resources is tainted. Add the right tolerations to your pod spec to schedule it and retrieve the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day15.tgz',
  },
  {
    day: 16,
    enabled: false,
    title: 'HPA Tuning',
    description: 'An HPA is scaling a deployment to max replicas but the pods are crashing under load. Fix the resource configuration and scaling thresholds so the app stabilizes and serves the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day16.tgz',
  },
  {
    day: 17,
    enabled: false,
    title: 'Namespace Isolation',
    description: 'The flag is in a pod in a locked-down namespace. You have access to a different namespace. Use RBAC and NetworkPolicies to reach across and extract the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day17.tgz',
  },
  {
    day: 18,
    enabled: false,
    title: 'Webhook Blocker',
    description: 'A ValidatingWebhookConfiguration is rejecting your deployments. Understand the webhook\'s rules and craft a deployment that passes validation to get the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day18.tgz',
  },
  {
    day: 19,
    enabled: false,
    title: 'Priority Preemption',
    description: 'Critical system pods are consuming all resources. Use PriorityClasses to preempt lower-priority workloads and schedule your pod to get the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day19.tgz',
  },
  {
    day: 20,
    enabled: false,
    title: 'Init Container Chain',
    description: 'A pod has three init containers that must run in sequence, each producing output for the next. One is broken. Fix the chain to produce the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day20.tgz',
  },
  {
    day: 21,
    enabled: false,
    title: 'CRD Operator',
    description: 'A custom operator watches a CRD. Create the correct custom resource spec to trigger the operator to generate a Secret containing the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day21.tgz',
  },
  {
    day: 22,
    enabled: false,
    title: 'Pod Security Standards',
    description: 'A namespace enforces restricted Pod Security Standards. Your deployment violates them. Fix the security context to comply while keeping the app functional and revealing the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day22.tgz',
  },
  {
    day: 23,
    enabled: false,
    title: 'Ephemeral Debug',
    description: 'A distroless pod has no shell but contains the flag on its filesystem. Use ephemeral debug containers to attach and extract it.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day23.tgz',
  },
  {
    day: 24,
    enabled: false,
    title: 'Cert Manager',
    description: 'A TLS certificate has expired and the Ingress is refusing HTTPS connections. Fix the Certificate resource and trigger renewal to restore access and get the flag.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day24.tgz',
  },
  {
    day: 25,
    enabled: false,
    title: 'Grand Finale',
    description: 'A multi-namespace environment is completely broken: RBAC is wrong, NetworkPolicies block everything, pods are misconfigured, and the flag is split across three services. Fix it all.',
    flagHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    chartUrl: 'https://example.com/charts/day25.tgz',
  },
];
