namespace: day21
appName: gitops-app
argocd:
  repoURL: https://github.com/adventofkube/adventofkube.git
  path: deploy/day21/apps     # BUG: actual path is "manifests/day21/apps"
  targetRevision: HEAD
  destination:
    namespace: argocd
