namespace: day08
appName: probe-app
image:
  repository: ghcr.io/adventofkube/day08
  tag: v1
liveness:
  path: /healthz
  initialDelaySeconds: 0
  periodSeconds: 3
  failureThreshold: 2
readiness:
  path: /healthz
  initialDelaySeconds: 0
  periodSeconds: 3
